### ISSUE TITLE
keycloak-import healthcheck to keycloak does not work

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#382]
### Describe the bug

In docker-compose-keycloak.yml, keycloak-import container waits for completion of booting keycloak container by
```
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/"]
      interval: 10s
      timeout: 5s
      retries: 5
```
Since keycloak 21, it seems that it does not work.

### Version

since keycloak 21

### Anything else?

Workaround is as follows:
1. remove healthcheck

```
    depends_on:
      keycloak:
        condition: service_healthy
```

If so, keycloak-import container start running and exits immediately because keycloak still not yet starts.

2. After booting keycloak, re-start keycloak-import container manually (e.g., docker desktop)
